build:
  image: node:5
  commands:
    - curl https://api.ciscospark.com/v1/messages -X POST -H "Authorization:Bearer $$SPARK_TOKEN" --data "roomId=$$SPARK_ROOM" --data "text=Repo $CI_REPO - Drone kicking off build $CI_BUILD_NUMBER"
    - npm install

publish:
  docker:
    repo: $$DOCKER_USERNAME/$$DOCKER_REPO
    tag: "$${BRANCH##feature/}"
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL



notify:
  webhook:
    debug: true
    image: plugins/drone-webhook
    when:
      success: true
      failure: true
    method: POST
    header:
      Content-type: application/json; charset=utf-8
      Authorization: Bearer $$SPARK_TOKEN
    urls:
      - https://api.ciscospark.com/v1/messages
    template: |
      {
        "roomId": "$$SPARK_ROOM",
        {{#success build.status}}
        "text": "Repo $CI_REPO - Drone confirms {{repo.full_name}} build {{build.number}} completed successfully.\nhttp://github.com/{{repo.full_name}}/commit/{{build.commit}}.\nhttp://$$DRONE_SERVER/{{repo.full_name}}/{{build.number}}."
        {{else}}
        "text": "Repo $CI_REPO - Drone blames {{build.author}} for breaking build {{build.number}}.\nhttp://github.com/{{repo.full_name}}/commit/{{build.commit}}.\nhttp://$$DRONE_SERVER/{{repo.full_name}}/{{build.number}}."
        {{/success}}
      }


